const fs = require("fs");

let links =[
    "/en/",
    "/produkt/dirndl-inkl-bluse/",
    "/produkt/lederhose/",
    "/produkt/lederhose-set/",
    "/produkt/haferlschuhe/",
    "/lederhosenverleih-preise/",
    "/lederhosenverleih-fuer-firmenkunden/",
    "/kollektion/",
    "/blog/",
    "/kontakt/",
    "/shop",
    "/warenkorb-2/",
    "/oeffnungszeiten",
    "/lederhosenverleih-fuer-firmenkunden",
    "/shop/",
    "/lederhosenverleih-preise",
    "/fruehlingsfest-2025-muenchen/",
    "/2025/02/",
    "/produkt/lederhose",
    "/produkt/lederhose-set",
    "/impressum/",
    "/datenschutzerklaerung/",
    "/en/pricing/",
    "/lederhosenverleih-preise/",
    "/produkt/lederhose/",
    "/produkt/lederhose-set/",
    "/produkt/haferlschuhe/",
    "/lederhosenverleih-fuer-firmenkunden/",
    "/kollektion/",
    "/blog/",
    "/kontakt/",
    "/shop",
    "/warenkorb-2/",
    "/produkt/lederhose",
    "/produkt/lederhose-set",
    "/dirndl-mieten",
    "/produkt/haferlschuhe",
    "/impressum/",
    "/datenschutzerklaerung/",
    "/lederhosenverleih-fuer-firmenkunden/",
    "/produkt/dirndl-inkl-bluse/",
    "/produkt/lederhose/",
    "/produkt/lederhose-set/",
    "/produkt/haferlschuhe/",
    "/lederhosenverleih-preise/",
    "/kollektion/",
    "/blog/",
    "/kontakt/",
    "/shop",
    "/warenkorb-2/",
    "/impressum/",
    "/datenschutzerklaerung/",
    "/en/gallery/",
    "/kollektion/",
    "/produkt/dirndl-inkl-bluse/",
    "/produkt/lederhose/",
    "/produkt/lederhose-set/",
    "/produkt/haferlschuhe/",
    "/lederhosenverleih-preise/",
    "/lederhosenverleih-fuer-firmenkunden/",
    "/blog/",
    "/kontakt/",
    "/shop",
    "/warenkorb-2/",
    "/impressum/",
    "/datenschutzerklaerung/",
    "/en/blog/",
    "/blog/",
    "/produkt/dirndl-inkl-bluse/",
    "/produkt/lederhose/",
    "/produkt/lederhose-set/",
    "/produkt/haferlschuhe/",
    "/lederhosenverleih-preise/",
    "/lederhosenverleih-fuer-firmenkunden/",
    "/kollektion/",
    "/kontakt/",
    "/shop",
    "/warenkorb-2/",
    "/category/unkategorisiert/",
    "/fruehlingsfest-2025-muenchen/",
    "/2025/02/",
    "/author/constantin/",
    "/fruehlingsfest-2024-uebernachtungstipps/",
    "/2024/02/",
    "/author/volker_quirling/",
    "/lederhose-leihen/",
    "/wann-beginnt-das-fruehlingsfest-2024-in-muenchen/",
    "/2024/01/",
    "/trachtenverleih-und-wirtshauswiesn-2020/",
    "/2020/09/",
    "/2016-die-wiesn-ist-vorbei/",
    "/2016/10/",
    "/tracht-und-kultur-in-muenchen/",
    "/2016/05/",
    "/go-kart-fahren-auf-dem-fruhlingsfest/",
    "/2016/02/",
    "/7-fakten-zur-auer-dult/",
    "/oktoberfest-countdown/",
    "/2016/01/",
    "/blog/page/2/",
    "/impressum/",
    "/datenschutzerklaerung/",
    "/en/",
    "/kontakt/",
    "/produkt/dirndl-inkl-bluse/",
    "/produkt/lederhose/",
    "/produkt/lederhose-set/",
    "/produkt/haferlschuhe/",
    "/lederhosenverleih-preise/",
    "/lederhosenverleih-fuer-firmenkunden/",
    "/kollektion/",
    "/blog/",
    "/shop",
    "/warenkorb-2/",
    "/impressum/",
    "/datenschutzerklaerung/"
]
const root = "https://bavarian-outfitters.de";
const staticExt = [".jpg", ".jpeg", ".png", ".gif", ".webp", ".svg", ".js", ".css", ".ico", ".woff", ".woff2"];

// lọc bỏ domain gốc, chỉ lấy phần path
let filtered = links
    .filter(l => {
        if (!(l.startsWith(root)) || l === root || l === root + "/") return false;

        // loại bỏ nếu link có đuôi trong danh sách staticExt
        let lower = l.toLowerCase();
        return !staticExt.some(ext => lower.endsWith(ext));
    })
    .map(l => l.replace(root, ""));

filtered = [...new Set(links)];

// lưu ra JSON
fs.writeFileSync("links1.json", JSON.stringify(filtered, null, 2), "utf8");

console.log("Đã lưu", filtered.length, "path vào links.json");
